### ISSUE TITLE
Retry fails in case of 429 error

### ISSUE THREAD

**Issue by erahamim** [okta/okta-sdk-java#259]
I'm using okta java sdk 1.3.0.
In case I send two request for verify factor with less than 30 seconds, I'm getting the below exception.

I would expect one of the two options:
1. Okta ecxception with 429 error code
2. Retry the request until it possible according to configuration.

I track the problem into HttpClientRequestExecutor.pauseBeforeRetry method.  When calling:
delay = get429DelayMillis(httpResponse); 
It return -1, and the code doesn't expect that.

The reason is: 
        String resetLimit = getOnlySingleHeaderValue(httpResponse,"**X-Rate-Limit-Reset**");
return null, as there is duplicate header "X-Rate-Limit-Reset" in the response from the server.

08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /api/v1/users/00uj6q6hiiflia18K0h7/factors/smsj6q4eohoN5DWyj0h7/verify HTTP/1.1[\r][\n]"
08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: dev-361990.oktapreview.com[\r][\n]"
08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip[\r][\n]"
08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept: application/json[\r][\n]"
08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: okta-auth-java/0.2.0 okta-sdk-java/1.3.0 spring-security/5.1.2.RELEASE spring/5.1.3.RELEASE spring-boot/2.1.1.RELEASE tomcat/9.0 java/11.0.1 Windows 10/10.0[\r][\n]"
08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Authorization: SSWS 00ceK4dyHJVJ_kwwBc1uAIXmMXHjROCAwSgZM3aFPe[\r][\n]"
08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 17[\r][\n]"
08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
08:34:40.411 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "{"passCode":null}"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 429 Too Many Requests[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Sun, 03 Feb 2019 06:34:42 GMT[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Okta-Request-Id: XFaLglSsDY@yoOqY4dy@tQAABSE[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "P3P: CP="HONK"[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Rate-Limit-Limit: 600[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Rate-Limit-Remaining: 594[\r][\n]"
### 08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Rate-Limit-Reset: 1549175723[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Cache-Control: no-cache, no-store[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Expires: 0[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Rate-Limit-Remaining: 0[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Rate-Limit-Limit: 1[\r][\n]"
### 08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Rate-Limit-Reset: 1549175695[\r][\n]"**
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Set-Cookie: sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/[\r][\n]"
08:34:40.816 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Set-Cookie: JSESSIONID=0ACCB87B9355B0B9855C1A2056A00677; Path=/; Secure; HttpOnly[\r][\n]"

Here is the exception:

08:09:55.481 [main] DEBUG com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor - 429 detected, will retry in -1ms, attempt number: 1
08:09:56.553 [main] WARN com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor - Unable to pause for retry: Cannot retry request, next request will exceed retry configuration.
com.okta.sdk.impl.http.RestException: Cannot retry request, next request will exceed retry configuration.
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.failedToRetry(HttpClientRequestExecutor.java:469)
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.pauseBeforeRetry(HttpClientRequestExecutor.java:455)
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:307)
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:414)
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$1(DefaultDataStore.java:298)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
	at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:330)
	at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:233)
	at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:228)
	at com.okta.sdk.impl.resource.user.factor.DefaultFactor.verify(DefaultFactor.java:326)
	at com.lilibank.common.okta.impl.factor.SmsFactorWrapper.verifyRequest(SmsFactorWrapper.java:192)
	at com.lilibank.common.okta.impl.factor.FactorService.verifyRequest(FactorService.java:144)
	at com.lilibank.common.unit.okta.OktaUtilMain.main(OktaUtilMain.java:468)
08:09:56.553 [main] WARN com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor - Unable to execute HTTP request: 
java.io.IOException: Attempted read from closed stream.
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:177)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
	at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:138)
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.toBytes(HttpClientRequestExecutor.java:563)
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.toSdkResponse(HttpClientRequestExecutor.java:580)
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:315)
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:414)
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$1(DefaultDataStore.java:298)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
	at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:330)
	at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:233)
	at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:228)
	at com.okta.sdk.impl.resource.user.factor.DefaultFactor.verify(DefaultFactor.java:326)
	at com.lilibank.common.okta.impl.factor.SmsFactorWrapper.verifyRequest(SmsFactorWrapper.java:192)
	at com.lilibank.common.okta.impl.factor.FactorService.verifyRequest(FactorService.java:144)
	at com.lilibank.common.unit.okta.OktaUtilMain.main(OktaUtilMain.java:468)
Disconnected from the target VM, address: '127.0.0.1:62880', transport: 'socket'
Exception in thread "main" com.okta.sdk.impl.http.RestException: Unable to execute HTTP request: Attempted read from closed stream.
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:346)
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:414)
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$1(DefaultDataStore.java:298)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
	at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:330)
	at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:233)
	at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:228)
	at com.okta.sdk.impl.resource.user.factor.DefaultFactor.verify(DefaultFactor.java:326)
	at com.lilibank.common.okta.impl.factor.SmsFactorWrapper.verifyRequest(SmsFactorWrapper.java:192)
	at com.lilibank.common.okta.impl.factor.FactorService.verifyRequest(FactorService.java:144)
	at com.lilibank.common.unit.okta.OktaUtilMain.main(OktaUtilMain.java:468)
Caused by: java.io.IOException: Attempted read from closed stream.
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:177)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
	at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:138)
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.toBytes(HttpClientRequestExecutor.java:563)
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.toSdkResponse(HttpClientRequestExecutor.java:580)
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:315)

This is a sample code that I use:

         Factor factor = ...  get factor from user
        VerifyFactorRequest verifyFactorRequest = authClient.instantiate(VerifyFactorRequest.class);
        verifyFactorRequest.setPassCode(null);
        VerifyFactorResponse response = factor.verify(verifyFactorRequest);

**Comment by bdemers** [comment]
@erahamim
Please create a support ticket with Okta: https://support.okta.com

I’ll keep this issue open to see if there is something better we can do in this case

**Comment by bdemers** [comment]
Proposed fix for the SDK (which is how this works in the .net SDK):
- take the smaller of the values and use that for the next request

**Comment by agiles231** [comment]
As a solution to rate limiting, I have implemented proktasy (https://github.com/agiles231/proktasy). Proktasy is a proxy between clients and Okta's REST API. It takes care of all rate limiting issues and handles a few edge cases that an API like this is incapable of handling. Feel free to check it out.
