### ISSUE TITLE
 com.okta.sdk.impl.http.RestException: Unable to execute HTTP request: timeout value is negative

### ISSUE THREAD

**Issue by hydanjan** [okta/okta-sdk-java#264]
I have getting this error while accessing the user related operations through Okta Java SDK.
Okta SDK Version : 1.2.0
Spring boot service in Docker container

Here is the full trace:
```
An unexpected error occurred: Unable to execute HTTP request: timeout value is negative,
,
com.okta.sdk.impl.http.RestException: Unable to execute HTTP request: timeout value is negative,
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:346) ~[okta-sdk-httpclient-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:414) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$getResourceData$0(DefaultDataStore.java:187) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.ds.DefaultDataStore$$Lambda$591.000000000C07A8D0.filter(Unknown Source) ~[na:na],
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:199) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:167) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:163) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.client.DefaultClient.listGroups(DefaultClient.java:627) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0],
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source) ~[na:na],
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192],
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192],
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) [spring-webmvc-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) [spring-webmvc-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) [spring-webmvc-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) [spring-boot-actuator-2.0.4.RELEASE.jar!/:2.0.4.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176) [spring-security-oauth2-2.2.2.RELEASE.jar!/:na],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) [spring-security-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE],
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:48) [spring-cloud-sleuth-core-2.0.2.RELEASE.jar!/:2.0.2.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:86) [brave-instrumentation-servlet-5.4.3.jar!/:na],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:155) [spring-boot-actuator-2.0.4.RELEASE.jar!/:2.0.4.RELEASE],
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:123) [spring-boot-actuator-2.0.4.RELEASE.jar!/:2.0.4.RELEASE],
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108) [spring-boot-actuator-2.0.4.RELEASE.jar!/:2.0.4.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192],
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192],
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.32.jar!/:8.5.32],
	at java.lang.Thread.run(Thread.java:813) [na:1.8.0_192],
Caused by: java.lang.IllegalArgumentException: timeout value is negative,
	at java.lang.Thread.sleep(Native Method) [na:1.8.0_192],
	at java.lang.Thread.sleep(Thread.java:943) [na:1.8.0_192],
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.pauseBeforeRetry(HttpClientRequestExecutor.java:450) ~[okta-sdk-httpclient-1.2.0.jar!/:1.2.0],
	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:307) ~[okta-sdk-httpclient-1.2.0.jar!/:1.2.0],
	... 124 common frames omitted,
```

**Comment by bdemers** [comment]
@hydanjan can you include the stack trace?

**Comment by hydanjan** [comment]
> @hydanjan can you include the stack trace?

@bdemers sorry.. was editing it. I have updated with the stack trace. Thanks!!

**Comment by bdemers** [comment]
How often are  you seeing this?
This could happen if your requests are returning 429s (rate limiting) and your server time is out of sync.

**Comment by hydanjan** [comment]
Here are some additional details: We are seeing this issue intermittently.

We have multiple micro-services deployed in a docker container and he is the workflow.
- Login to front end which is angular based application
- Front-end calls a micro-service (its a kind of proxy) to list okta users
- Back-end service( Service A) calls another API, which is also a micro-service (Service B) which actually talks to Okta for all user related operations.
- It returns the list of users. Then after 5 mins if we refresh the page or login again, that's when we see the logged exception and that is occurring in Service B.
- If we, refresh the page again as we wait for the response, it lists the users.
- I think we made sure about the limits and it didn't exceed.

I have tried with multiple combinations for the below settings and still see the same issue. 

```
 @Bean
    public Client oktaClient() {
        logger.debug("creating the oktaClient bean.");
        ClientCredentials clientCredentials = new TokenClientCredentials(oktaApiToken);
        return Clients
                .builder()
                .setCacheManager(Caches.newDisabledCacheManager())
                .setOrgUrl(oktaOrgUrl)
                .setClientCredentials(clientCredentials)
                .setConnectionTimeout(60)
                .setRetryMaxElapsed(30)
                .setRetryMaxAttempts(3)
                .build();
    }
```
The only difference is if i set setRetryMaxElapsed and setConnectionTimeout to some value, it changes the exception to Read timed out.

```

com.okta.sdk.impl.http.RestException: Unable to execute HTTP request: Read timed out


	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:346) ~[okta-sdk-httpclient-1.2.0.jar!/:1.2.0]


	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:414) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0]


	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$getResourceData$0(DefaultDataStore.java:187) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0]


	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0]


	at com.okta.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:199) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0]


	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:167) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0]


	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:163) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0]


	at com.okta.sdk.impl.client.DefaultClient.listGroups(DefaultClient.java:627) ~[okta-sdk-impl-1.2.0.jar!/:1.2.0]

-------------------------


Caused by: java.net.SocketTimeoutException: Read timed out


	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_202]


	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_202]


	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_202]


	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_202]


	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_202]


	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_202]


	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) ~[na:1.8.0_202]


	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933) ~[na:1.8.0_202]


	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_202]


	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.10.jar!/:4.4.10]


	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore-4.4.10.jar!/:4.4.10]


	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282) ~[httpcore-4.4.10.jar!/:4.4.10]


	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient-4.5.3.jar!/:4.5.3]


	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.3.jar!/:4.5.3]


	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.10.jar!/:4.4.10]


	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.10.jar!/:4.4.10]


	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165) ~[httpclient-4.5.3.jar!/:4.5.3]


	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.10.jar!/:4.4.10]


	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.10.jar!/:4.4.10]


	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.3.jar!/:4.5.3]


	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar!/:4.5.3]


	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar!/:4.5.3]


	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar!/:4.5.3]


	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar!/:4.5.3]


	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar!/:4.5.3]


	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.3.jar!/:4.5.3]


	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.3.jar!/:4.5.3]


	at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:328) ~[okta-sdk-httpclient-1.2.0.jar!/:1.2.0]


	... 120 common frames omitted
```

Hope that helps. Please let me know for any additional information. Thanks!!

**Comment by bdemers** [comment]
Is this running in a public cloud? what time servers are you using?

**Comment by hydanjan** [comment]
Yes, its running in a public cloud - Azure. We are using the default time server from ubuntu - ntp.ubuntu.com

**Comment by bdemers** [comment]
Have you tried extending the connection timeout?

**Comment by hydanjan** [comment]
Yes, I did. I have tried with 300 secs and with out setting the time out as well. Still the same issue.

**Comment by bdemers** [comment]
Are you able to make other connections from that box? try a `curl` to `/api/v1/users` (even without an API token for this test should be enough`, probably time it too: `time curl your-domain/api/v1/users`

**Comment by DougDouglassHD** [comment]
Adding another data point that we are also intermittently (2-12/day going back to 2018-09) experiencing this same error:
```
java.lang.IllegalArgumentException: timeout value is negative
        at java.lang.Thread.sleep(Native Method)
        at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.pauseBeforeRetry(HttpClientRequestExecutor.java:450)
        at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:307)
        at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:414)
        at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$1(DefaultDataStore.java:298)
        at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
        at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34)
        at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
        at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42)
        at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
        at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:330)
        at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:249)
        at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:243)
        at com.okta.sdk.impl.resource.user.DefaultUser.update(DefaultUser.java:861)
```

I was only made aware of the issue today, so not much diagnosis has yet been done on our part.

The app, a customized version of CAS SSO server, is running on our own infrastructure. The app is effectively doing upserts of authenticated users into our Okta org as we migrate off of our legacy SSO infrastructure.

Your suggested ```curl``` tests from the server hosting the app produce consistent results:
```
$ time curl https://********.okta.com/api/v1/users
{"errorCode":"E0000005","errorSummary":"Invalid session","errorLink":"E0000005","errorId":"oae93G_xBv3QD2zq5nEHALXzw","errorCauses":[]}
real	0m0.335s
user	0m0.069s
sys	0m0.068s
```

**Comment by bdemers** [comment]
I'm digging around in this now

**Comment by bdemers** [comment]
@DougDouglassHD which version was that stacktrace from?

**Comment by DougDouglassHD** [comment]
Okta SDK version: 1.2.0

**Comment by bdemers** [comment]
@DougDouglassHD give the latest version 1.4.1 a shot

I've also found a few edge cases that #267 fixes, feel free to comment on that one too
