### ISSUE TITLE
Seems like sources for http://central.maven.org/maven2/com/okta/sdk/okta-sdk-api/1.5.2/ are not correctly linked

### ISSUE THREAD

**Issue by seregasheypak** [okta/okta-sdk-java#285]
Hi, 
should we use add https://maven.apache.org/plugins/maven-source-plugin/usage.html in order to link sources at artifactory level? My JIdea refuses to download artifacts.

**Comment by bdemers** [comment]
It _should_ just work. Does IntelliJ give you an error?

**Comment by bdemers** [comment]
@seregasheypak did you get this resolved?  Or am I thinking about another thread? 😄

**Comment by seregasheypak** [comment]
`chmod 755 /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/security/jssecacerts`
does the trick. 

Here is the root cause, JIdea starts 
```
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2019-05-27 22:07:28,799 [101908648]   INFO - s.plugins.gradle.GradleManager - Instructing gradle to use java from /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home 
2019-05-27 22:07:28,800 [101908649]   INFO - s.plugins.gradle.GradleManager - Instructing gradle to use java from /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home 
2019-05-27 22:07:28,832 [101908681]   INFO - xecution.GradleExecutionHelper - Passing command-line args to Gradle Tooling API: --init-script /private/var/folders/jn/n_2j5x257378j54drw3vvrc80000gn/T/ijmiscinit.gradle 
2019-05-27 22:07:33,326 [101913175]   WARN - nal.AbstractExternalSystemTask - /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/security/jssecacerts (Permission denied) 
com.intellij.openapi.externalSystem.model.ExternalSystemException: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/security/jssecacerts (Permission denied)
	at com.android.tools.idea.gradle.project.sync.idea.ProjectImportErrorHandler.getUserFriendlyError(ProjectImportErrorHandler.java:72)


at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(DefaultCacheAwareExternalResourceAccessor.java:81)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadByCoords(DefaultExternalResourceArtifactResolver.java:133)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(DefaultExternalResourceArtifactResolver.java:97)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.resolveArtifact(DefaultExternalResourceArtifactResolver.java:64)
	at org.gradle.api.internal.artifacts.repositories.metadata.AbstractRepositoryMetadataSource.parseMetaDataFromArtifact(AbstractRepositoryMetadataSource.java:69)
	at org.gradle.api.internal.artifacts.repositories.metadata.AbstractRepositoryMetadataSource.create(AbstractRepositoryMetadataSource.java:59)
	at org.gradle.api.internal.artifacts.repositories.metadata.DefaultMavenPomMetadataSource.create(DefaultMavenPomMetadataSource.java:38)
	at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver.resolveStaticDependency(ExternalResourceResolver.java:243)
	at org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver.doResolveComponentMetaData(MavenResolver.java:126)

```
`ProjectImportErrorHandler.getUserFriendlyError` wasn't friendly enough. I have no idea what it happens to JIdea.

**Comment by bdemers** [comment]
Thanks for the update!
