### ISSUE TITLE
Attempt to use AutoRest to generate PowerShell Module fails

### ISSUE THREAD

**Issue by kevinblumenfeld** [okta/okta-sdk-java#293]
Referencing issue: [https://github.com/Azure/autorest.powershell/issues/385](https://github.com/Azure/autorest.powershell/issues/385)

Was hoping Okta et al. could have a quick look to make sure its not something in the yaml.  Thank you for your time in advance.

Attempting to generate PowerShell module with spec: https://github.com/okta/okta-sdk-java/blob/master/src/swagger/api.yaml

```
PS C:\Scripts> autorest --reset
AutoRest code generation utility [version: 3.0.5221; node: v10.16.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Cleared the AutoRest extension folder.
On the next run, extensions will be reacquired from the repository.
 autorest --powershell --input-file:./okta.yaml --clear-output-folder
AutoRest code generation utility [version: 3.0.5221; node: v10.16.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest-core@3.0.5504\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5504)
   Installing AutoRest extension '@microsoft.azure/autorest.powershell' (beta)
   Installed AutoRest extension '@microsoft.azure/autorest.powershell' (beta->2.0.547)
   Installing AutoRest extension '@microsoft.azure/autorest.remodeler' (beta)
   Installed AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->2.0.317)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta)
   Installed AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->2.0.350)
WARNING (): Operation forgot/password is inferred without finding action.
    - code-model-v3-tweakcodemodel.yaml:1:1

WARNING (): Operation expire/password is inferred without finding action.
    - code-model-v3-tweakcodemodel.yaml:1:1

WARNING (): Operation unsuspend/user is inferred without finding action.
    - code-model-v3-tweakcodemodel.yaml:1:1

ERROR (UnknownJsonType/LLCS2000): Schema 'BasicAuthApplicationName' is declared with invalid type 'undefined'
    - code-model-v3-modifiers.yaml:1:1
C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\dist\plugin-llcsharp.js - Error: Unknown Model. Fatal.
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\schema\schema-resolver.ts:145:11)
    at ModelsNamespace.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:69:30)
    at ModelInterface.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\interface.ts:111:58)
    at new ModelClass (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\model-class.ts:113:198)
    at ModelsNamespace.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:80:65)
    at new ModelsNamespace (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:56:12)
    at Project.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\project.ts:69:46)/Unknown Model. Fatal.
PLUGIN FAILURE: Unknown Model. Fatal., Error: Unknown Model. Fatal.
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\schema\schema-resolver.ts:145:11)
    at ModelsNamespace.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:69:30)
    at ModelInterface.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\interface.ts:111:58)
    at new ModelClass (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\model-class.ts:113:198)
    at ModelsNamespace.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:80:65)
    at new ModelsNamespace (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:56:12)
    at Project.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\project.ts:69:46), {}
FATAL: Error: Unknown Model. Fatal.
C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest-core@3.0.5504\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}

ERROR (UnknownJsonType/LLCS2000): Schema 'ApplicationSettingsApplication' is declared with invalid type 'undefined'
    - code-model-v3-add-azure-completers.yaml:1:1
C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\dist\plugin-powershell.js - FAILURE  {} Error: Unknown Model. Fatal.
    at PSSchemaResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.csharp-v2\schema\schema-resolver.ts:145:11)
    at PSSchemaResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\project.ts:45:18)
    at CmdletClass.addPowershellParameters (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:886:74)
    at CmdletClass.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:133:10)
    at CmdletNamespace.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\namespaces\cmdlet.ts:31:110)
PLUGIN FAILURE: Unknown Model. Fatal., Error: Unknown Model. Fatal.
    at PSSchemaResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.csharp-v2\schema\schema-resolver.ts:145:11)
    at PSSchemaResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\project.ts:45:18)
    at CmdletClass.addPowershellParameters (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:886:74)
    at CmdletClass.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:133:10)
    at CmdletNamespace.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\namespaces\cmdlet.ts:31:110), {}
FATAL: Error: Unknown Model. Fatal.
C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest-core@3.0.5504\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin llcsharp reported failure. / Error: Plugin llcsharp reported failure.
    at C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest-core@3.0.5504\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
  Error: Plugin llcsharp reported failure.```

**Comment by bdemers** [comment]
Hey @kevinblumenfeld ! 
Thanks for trying taking a look at our swagger spec.

My guess is that the lib you are using expects a `type: object` in `ApplicationSettingsApplication`:
https://github.com/okta/okta-sdk-java/blob/master/src/swagger/api.yaml#L2958

I know the Java Swagger lib defaults to this.  I'd suggest try adding that property.  Let us know.
If it works it's something easy we can fix.

cc: @OkGoDoIt you might see something in that PowerShell stacktrace that I don't

**Comment by kevinblumenfeld** [comment]
@bdemers @OkGoDoIt thank you so much for your reply. Could I ask where would I add that to the yaml file?

**Comment by bdemers** [comment]
Hey @kevinblumenfeld 
Just under: https://github.com/okta/okta-sdk-java/blob/master/src/swagger/api.yaml#L2958
Similar to how it is defined in: https://github.com/okta/okta-sdk-java/blob/master/src/swagger/api.yaml#L2955

Keep us posted!

**Comment by kevinblumenfeld** [comment]
@OkGoDoIt @bdemers thank you so much for your reply.  Would you be able to check out the comments from the AutoRest author to see if we are missing something?  https://github.com/Azure/autorest.powershell/issues/385#issuecomment-506883417 .  Not sure I can help out, but would be happy to in any way I can.  Again thank you for your responsiveness.

**Comment by bdemers** [comment]
@kevinblumenfeld That does look like an issue, I'll see what we can do.

Thanks for digging into this!

**Comment by gabrielsroka** [comment]
Hi @kevinblumenfeld 

I'd be interested in your use case, since I'm also interested in Swagger -> PowerShell.

I created 
https://github.com/gabrielsroka/OktaAPI.psm1
but it was coded by hand.

**Comment by kevinblumenfeld** [comment]
Hi @gabrielsroka !
I would really love to automate the creation of a module. I have manually created a several functions 
[https://github.com/kevinblumenfeld/Posh365/tree/master/Posh365/Public/Okta](https://github.com/kevinblumenfeld/Posh365/tree/master/Posh365/Public/Okta)
and would like to continue, however, automating via autorest would be ideal!

**Comment by kevinblumenfeld** [comment]
@bdemers is there another tool to automate the creation of a PowerShell module.. I remember you commented in the AutoRest forum about an "extension".  How is that used?

**Comment by bdemers** [comment]
@kevinblumenfeld sorry, the "extension" I was referring to was part of the swagger spec, basically, any property that starts with `x-` is an extension.

I'm going to close this issue, and we can continue the discussion in https://github.com/gabrielsroka/OktaAPI.psm1 as need.

Thanks @gabrielsroka and @kevinblumenfeld !
