### ISSUE TITLE
JDK 11 - Unable to convert InputStream String to Map

### ISSUE THREAD

**Issue by dmhishi** [okta/okta-sdk-java#312]
**Error when attemping an Okta calls using the client:**

```txt
Exception in thread "main" com.okta.sdk.impl.ds.MarshalingException: Unable to convert InputStream String to Map.
	at com.okta.sdk.impl.ds.JacksonMapMarshaller.unmarshal(JacksonMapMarshaller.java:100)
	at com.okta.sdk.impl.ds.DefaultDataStore.getBody(DefaultDataStore.java:466)
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:443)
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$getResourceData$0(DefaultDataStore.java:193)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
	at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:205)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:174)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:169)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:165)
	at com.okta.sdk.impl.client.DefaultClient.listApplications(DefaultClient.java:163)
	at com.gs.authn.JDK11Okta.App.main(App.java:16)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Bad': was expecting ('true', 'false' or 'null')
 at [Source: (ByteArrayInputStream); line: 1, column: 5]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3532)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2627)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:832)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:729)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at com.okta.sdk.impl.ds.JacksonMapMarshaller.unmarshal(JacksonMapMarshaller.java:86)
	... 14 more
```
**Sample Code:**
```java
import com.okta.sdk.authc.credentials.TokenClientCredentials;
import com.okta.sdk.client.Client;
import com.okta.sdk.client.Clients;
import com.okta.sdk.client.Proxy;
import com.okta.sdk.resource.application.ApplicationList;
public class App {
    public static void main(String[] args) {
        Client client = Clients.builder()
                .setProxy(new Proxy("localhost", 8585))
                .setOrgUrl("https://tenantName.oktapreview.com")
                .setClientCredentials(new TokenClientCredentials("API_TOKEN_HERE"))
                .build();
        ApplicationList applications = client.listApplications();
        applications.forEach(application -> System.out.println(application.getId()));
    }
}
```
**POM:**
```xml
<?xml version="1.0" encoding="UTF-8"?><b>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.company</groupId>
    <artifactId>JDK11Okta</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <okta.version>1.5.2</okta.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.okta.sdk</groupId>
            <artifactId>okta-sdk-api</artifactId>
            <version>${okta.version}</version>
        </dependency>
        <dependency>
            <groupId>com.okta.sdk</groupId>
            <artifactId>okta-sdk-impl</artifactId>
            <version>${okta.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.okta.sdk</groupId>
            <artifactId>okta-sdk-httpclient</artifactId>
            <version>${okta.version}</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by bdemers** [comment]
@dmhishi just to clarify, are you saying this only happens with JDK 11?

**Comment by bdemers** [comment]
Also, can you grab the resource body with the `"Bad"` value, the easiest option might be using Postman or cUrl/Httpie

**Comment by dmhishi** [comment]
> @dmhishi just to clarify, are you saying this only happens with JDK 11?

Yes, it's working with Java 8. I have tried other simple API calls and they're all failing.


> Also, can you grab the resource body with the `"Bad"` value, the easiest option might be using Postman or cUrl/Httpie

There is no request body for this operation. The SDK is making an internal call to /api/v1/apps.

**Comment by bdemers** [comment]
Can you turn on the wire log (assuming you are using httpclient https://hc.apache.org/httpcomponents-client-4.5.x/logging.html)

Does the same thing happen with Java 11 if you don't use a proxy?

**Comment by dmhishi** [comment]
The issue was related to our internal proxy, successfully tested the calls using a different proxy. Thank you.
