### ISSUE TITLE
Failed to initialize DefaultDataStore in war-assembly

### ISSUE THREAD

**Issue by g4s8** [okta/okta-sdk-java#315]
I'm using Jetty [livewar assembly](https://github.com/jetty-project/embedded-jetty-live-war) to run embedded Jetty server as `war`.
It contains maven modules: webapp, server and two helper modules. I'm using Okta SDK from `webapp` module, `pom.xml` [is configured](https://github.com/g4s8/so57760064/blob/master/thewebapp/pom.xml#L30) as in SDK README. When I'm trying to create new `Okta` instance using `Clients.builder()` it throws this exception:
```
java.lang.ExceptionInInitializerError
        at com.okta.sdk.impl.ds.DefaultDataStore.<clinit>(DefaultDataStore.java:94)
        at com.okta.sdk.impl.client.BaseClient.createDataStore(BaseClient.java:80)
        at com.okta.sdk.impl.client.BaseClient.<init>(BaseClient.java:73)
        at com.okta.sdk.impl.client.AbstractClient.<init>(AbstractClient.java:60)
        at com.okta.sdk.impl.client.DefaultClient.<init>(DefaultClient.java:117)
        at com.okta.sdk.impl.client.DefaultClientBuilder.build(DefaultClientBuilder.java:322)
        at demo.jetty.TimeServlet.doGet(TimeServlet.java:34)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:856)
        at ...
        at java.lang.Thread.run(Thread.java:748)
Caused by: 
java.lang.NullPointerException
        at com.okta.sdk.impl.http.support.UserAgent.getVersionInfoInManifest(UserAgent.java:384)
        at com.okta.sdk.impl.http.support.UserAgent.getFullEntryStringUsingManifest(UserAgent.java:274)
        at com.okta.sdk.impl.http.support.UserAgent.getWebServerString(UserAgent.java:240)
        at com.okta.sdk.impl.http.support.UserAgent.createUserAgentString(UserAgent.java:141)
        at com.okta.sdk.impl.http.support.UserAgent.<clinit>(UserAgent.java:125)
        at com.okta.sdk.impl.ds.DefaultDataStore.<clinit>(DefaultDataStore.java:94)
        at com.okta.sdk.impl.client.BaseClient.createDataStore(BaseClient.java:80)
        at com.okta.sdk.impl.client.BaseClient.<init>(BaseClient.java:73)
        at com.okta.sdk.impl.client.AbstractClient.<init>(AbstractClient.java:60)
        at com.okta.sdk.impl.client.DefaultClient.<init>(DefaultClient.java:117)
        at com.okta.sdk.impl.client.DefaultClientBuilder.build(DefaultClientBuilder.java:322)
        at demo.jetty.TimeServlet.doGet(TimeServlet.java:34)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at ...
        at java.lang.Thread.run(Thread.java:748)
```

I created example project to reproduce this issue (all setup steps are described in the README): https://github.com/g4s8/so57760064

It seems `DefaultDataStore` can't find some `VersionInfoInManifest`, but I didn't find this method `getVersionInfoInManifest` in this repository.

**Comment by bdemers** [comment]
@g4s8 Thanks for the repro case! I'll take a look!

**Comment by bdemers** [comment]
Thanks for the report @g4s8! We get this in for our next release.

I'll also suggest avoiding using the shade plugin to create uberjars/wars
I've used the spring-boot plugin's repackage goal (on non-spring projects as well as spring projects).  It avoids unpacking your jars and dumping them in the same directory.  Which is both faster at build time, and gives you a more predictable binary.

I haven't actually tried using it to build war files though, IIRC it uses this project:
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-tools/spring-boot-loader

**Comment by g4s8** [comment]
@bdemers thanks! Will take a look

**Comment by g4s8** [comment]
@bdemers Hi, can you please release these changes with new version?
