### ISSUE TITLE
OKTA_CLIENT_TOKEN env var prevents Spring Boot app from starting in Docker

### ISSUE THREAD

**Issue by garcger-blk** [okta/okta-sdk-java#483]
While I'm able to specify these environment variables:

- `OKTA_CLIENT_ORGURL`
- `OKTA_CLIENT_PROXY_HOST`
- `OKTA_CLIENT_PROXY_PORT`
- `OKTA_OAUTH2_AUDIENCE`

as soon as I specify `OKTA_CLIENT_TOKEN` the app fails to start in Docker--here's the log:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.4.RELEASE)
2020-11-17 03:06:52,090 (main:[]) INFO  [***] Starting *** v2020.12.0-SNAPSHOT on 5bdff47b76-rkdrd with PID 29 (/apps/apache-tomcat/web/WEB-INF/classes started by ebizrt in /apps/apache-tomcat)
2020-11-17 03:06:52,090 (main:[]) DEBUG [***] Running with Spring Boot v2.3.4.RELEASE, Spring v5.2.9.RELEASE
2020-11-17 03:06:52,090 (main:[]) INFO  [***] The following profiles are active: ***,cloud,session-replication
2020-11-17 03:06:53,522 (main:[]) ERROR [org.springframework.boot.SpringApplication] Application run failed java.lang.IllegalStateException: Error processing condition on com.okta.spring.boot.sdk.OktaSdkConfig.oktaSdkClientCredentials
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:184)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:96)
2020-11-17 03:06:53,527 (main:[]) WARN  [org.springframework.boot.SpringApplication] Unable to close ApplicationContext java.lang.IllegalStateException: Failed to introspect Class [com.okta.spring.boot.sdk.OktaSdkConfig] from ClassLoader [ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@5a8806ef
]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358)
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:414)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:742)
```
<img width="628" alt="Screen Shot 2020-11-16 at 7 55 05 PM" src="https://user-images.githubusercontent.com/69658294/99347226-69588800-284b-11eb-9ff5-3139630c6904.png">

**Comment by sergiishamrai-okta** [comment]
Thank you for the question!  Can you help me understand more about the issue you experiencing?
Does your application work correctly outside of Docker container?

**Comment by bdemers** [comment]
Can you share the full stacktrace?

You also may need to include the following dependency:
```xml
<dependency>
    <groupId>com.okta.spring</groupId>
    <artifactId>okta-spring-sdk</artifactId>
</dependency>
```

**Comment by garcger-blk** [comment]
> Thank you for the question! Can you help me understand more about the issue you experiencing?
> Does your application work correctly outside of Docker container?

Unfortunately, I'm only able to get an older version running outside of Docker.

Here's the stacktrace when I define `OKTA_CLIENT_TOKEN` env var:
```
  .   ____          _            __ _ _
/\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
\\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/
:: Spring Boot ::        (v2.2.6.RELEASE)
 
2020-11-16 17:05:38.024  INFO 47312 --- [           main] com.bfm.idm.api.Application              : Starting Application on SFOMD2279334 with PID 47312 (C:\MyFolder\MyRepositories\Others\idm-platform\modules\api\target\classes started by snataraj in C:\MyFolder\MyRepositories\Others\idm-platform\modules\api)
2020-11-16 17:05:38.041  INFO 47312 --- [           main] com.bfm.idm.api.Application              : No active profile set, falling back to default profiles: default
2020-11-16 17:05:41.821  INFO 47312 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-11-16 17:05:41.845  INFO 47312 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'objectPostProcessor' of type [org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-11-16 17:05:41.853  INFO 47312 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@340a8894' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-11-16 17:05:41.856  INFO 47312 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-11-16 17:05:41.871  INFO 47312 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-11-16 17:05:44.324  INFO 47312 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8082 (http)
2020-11-16 17:05:44.383  INFO 47312 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-11-16 17:05:44.384  INFO 47312 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.33]
2020-11-16 17:05:45.125  INFO 47312 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-11-16 17:05:45.125  INFO 47312 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 6922 ms
2020-11-16 17:05:51.584  INFO 47312 --- [           main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2020-11-16 17:05:51.793 DEBUG 47312 --- [           main] o.s.s.a.i.a.MethodSecurityInterceptor    : Validated configuration attributes
2020-11-16 17:05:52.125  INFO 47312 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-11-16 17:05:53.135  WARN 47312 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'oktaSdkClient' defined in class path resource [com/okta/spring/boot/sdk/OktaSdkConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.okta.sdk.client.Client]: Factory method 'oktaSdkClient' threw exception; nested exception is java.lang.IllegalArgumentException: Your Okta URL is missing. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain
2020-11-16 17:05:53.135  INFO 47312 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-11-16 17:05:53.150  INFO 47312 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-11-16 17:05:53.190  INFO 47312 --- [           main] ConditionEvaluationReportLoggingListener :
 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-11-16 17:05:53.215 ERROR 47312 --- [           main] o.s.boot.SpringApplication               : Application run failed
 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'oktaSdkClient' defined in class path resource [com/okta/spring/boot/sdk/OktaSdkConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.okta.sdk.client.Client]: Factory method 'oktaSdkClient' threw exception; nested exception is java.lang.IllegalArgumentException: Your Okta URL is missing. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain
      at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
      at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
      at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
      at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
      at com.bfm.idm.api.Application.main(Application.java:18) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.okta.sdk.client.Client]: Factory method 'oktaSdkClient' threw exception; nested exception is java.lang.IllegalArgumentException: Your Okta URL is missing. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain
      at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      ... 19 common frames omitted
Caused by: java.lang.IllegalArgumentException: Your Okta URL is missing. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain
      at com.okta.commons.configcheck.ValidationResponse.lambda$ifInvalidThrow$0(ValidationResponse.java:44) ~[okta-config-check-1.1.1.jar:1.1.1]
      at com.okta.commons.configcheck.ValidationResponse.ifInvalid(ValidationResponse.java:50) ~[okta-config-check-1.1.1.jar:1.1.1]
      at com.okta.commons.configcheck.ValidationResponse.ifInvalidThrow(ValidationResponse.java:43) ~[okta-config-check-1.1.1.jar:1.1.1]
      at com.okta.commons.configcheck.ConfigurationValidator.assertOrgUrl(ConfigurationValidator.java:74) ~[okta-config-check-1.1.1.jar:1.1.1]
      at com.okta.sdk.impl.client.DefaultClientBuilder.setOrgUrl(DefaultClientBuilder.java:327) ~[okta-sdk-impl-1.5.4.jar:1.5.4]
      at com.okta.spring.boot.sdk.OktaSdkConfig.oktaSdkClient(OktaSdkConfig.java:71) ~[okta-spring-sdk-1.4.0.jar:1.4.0]
      at com.okta.spring.boot.sdk.OktaSdkConfig$$EnhancerBySpringCGLIB$$40ad3d9e.CGLIB$oktaSdkClient$0(<generated>) ~[okta-spring-sdk-1.4.0.jar:1.4.0]
      at com.okta.spring.boot.sdk.OktaSdkConfig$$EnhancerBySpringCGLIB$$40ad3d9e$$FastClassBySpringCGLIB$$4d9ef2c9.invoke(<generated>) ~[okta-spring-sdk-1.4.0.jar:1.4.0]
      at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      at com.okta.spring.boot.sdk.OktaSdkConfig$$EnhancerBySpringCGLIB$$40ad3d9e.oktaSdkClient(<generated>) ~[okta-spring-sdk-1.4.0.jar:1.4.0]
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_211]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_211]
      at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_211]
      at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
      ... 20 common frames omitted
```

**Comment by garcger-blk** [comment]
> Can you share the full stacktrace?
> 
> You also may need to include the following dependency:
> 
> ```
> <dependency>
>     <groupId>com.okta.spring</groupId>
>     <artifactId>okta-spring-sdk</artifactId>
> </dependency>
> ```

Unfortunately, that is the full stacktrace. Please see my reply to **sergiishamrai-okta** where I provide the stacktrace for an older version of the app that I'm still able to run outside of Docker 

I tried adding the dependency, but get the same error at startup. Doesn't `okta-spring-sdk` come with `okta-spring-boot-starter` (which is used by our app)

**Comment by arvindkrishnakumar-okta** [comment]
@garcger-blk In Docker env, which version of `okta-sdk-java` does your:
a) working app use 
b) non-working app use

**Comment by garcger-blk** [comment]
@arvindkrishnakumar-okta 
a) 1.4.0
b) 1.4.0

We're not able to run the latest version of our app (which uses the latest `okta-spring-sdk` 1.4.0) outside of Docker due to dependencies on other dockerized components.

Our app will only ever run in Docker/Openshift.

The stacktrace I provided in this [reply](https://github.com/okta/okta-sdk-java/issues/483#issuecomment-729083466) is an older version of our app, which does not start when we specify _only_ `OKTA_CLIENT_TOKEN`, but _does work_ when specifying both `OKTA_CLIENT_TOKEN` and `OKTA_CLIENT_ORGURL`

Unfortunately, specifying both `OKTA_CLIENT_TOKEN` and `OKTA_CLIENT_ORGURL` when running in Docker results in the stacktrace in my initial [comment](https://github.com/okta/okta-sdk-java/issues/483#issue-744392499)

**Comment by garcger-blk** [comment]
@bdemers could [this](https://github.com/okta/okta-spring-boot/issues/142) be related?

**Comment by garcger-blk** [comment]
@bdemers, @sergiishamrai-okta, @arvindkrishnakumar-okta  here's a better stacktrace from Docker (only happens when specifying `OKTA_CLIENT_TOKEN` -- though I'm able to override `OKTA_CLIENT_ORGURL`, `OKTA_CLIENT_PROXY_HOST`, `OKTA_CLIENT_PROXY_PORT`, `OKTA_OAUTH2_AUDIENCE`):
```
       Caused by: java.lang.IllegalStateException: Error processing condition on com.okta.spring.boot.sdk.OktaSdkConfig.oktaSdkClie
ntCredentials
                at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60)
                at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
                at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(Co
nfigurationClassBeanDefinitionReader.java:184)
                at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfiguration
Class(ConfigurationClassBeanDefinitionReader.java:144)
                at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationCl
assBeanDefinitionReader.java:120)
                at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(Configuration
ClassPostProcessor.java:331)
                at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(Configur
ationClassPostProcessor.java:236)
                at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(
PostProcessorRegistrationDelegate.java:280)
                at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcess
orRegistrationDelegate.java:96)
                at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicatio
nContext.java:707)
                at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533)
                at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicati
onContext.java:143)
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
                at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:1
73)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBoot
ServletInitializer.java:153)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.
java:95)
                at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5128)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                ... 38 more
        Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.okta.spring.boot.sdk.OktaSdkConfig] from ClassLo
ader [ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@5a8806ef
]
                at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
                at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358)
                at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:414)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(Abs
tractAutowireCapableBeanFactory.java:742)
                at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAuto
wireCapableBeanFactory.java:741)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowire
CapableBeanFactory.java:680)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapa
bleBeanFactory.java:648)
                at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1614)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFac
tory.java:523)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFacto
ry.java:495)
                at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:238
)
                at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:231)
                at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:221)
                at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:169)
                at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:144)
                at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
                ... 59 more
        Caused by: java.lang.NoClassDefFoundError: com/okta/sdk/client/Proxy
                at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
                at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
                at java.base/java.lang.Class.getDeclaredMethods(Unknown Source)
                at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463)
                ... 75 more
        Caused by: java.lang.ClassNotFoundException: com.okta.sdk.client.Proxy
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
                ... 79 more
18-Nov-2020 02:17:42.677 INFO [main] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of deployment descriptor [/a
pps/apache-tomcat/tomcat/conf/Catalina/localhost/ROOT.xml] has finished in [6,517] ms
18-Nov-2020 02:17:42.688 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-1776"]
18-Nov-2020 02:17:42.693 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [6572] milliseconds

```

**Comment by bdemers** [comment]
It's a dependency mismatch. The Okta Spring Boot Starter currently supports The 1.x version of the Okta Java SDK. If you are using the 2.x version would cause this problem (we are currently working on updating this)

**Comment by garcger-blk** [comment]
@arvindkrishnakumar-okta 

> Also, does you app run fine outside the docker environment with latest `okta-spring-sdk`?

(for completeness) we were finally able to run the latest version of our app outside of docker -- and we replicated the issue

**Comment by garcger-blk** [comment]
@bdemers 

> It's a dependency mismatch. The Okta Spring Boot Starter currently supports The 1.x version of the Okta Java SDK. If you are using the 2.x version would cause this problem (we are currently working on updating this)
> 
> If you are NOT using the 2.x version and you still see this problem, can list your Okta related dependencies (you can run `mvn dependency:tree` (or the gradle equivalent)

we're definitely using 2.x -- is this the [related issue](https://github.com/okta/okta-spring-boot/issues/176)?

**Comment by arvindkrishnakumar-okta** [comment]
@garcger-blk Thanks! If you're using 2.x of `okta-sdk-java`, it will not work. The `NoClassDefFoundError` for `com.okta.sdk.client.Proxy` you reported above is expected. We're still in the process of upgrading `okta-spring-boot` to use `okta-sdk-java` version 2.x. This upgrade should resolve your dependency issue.

**Comment by bdemers** [comment]
@garcger-blk until we have that one fixed, you can either:
1. Use the 1.x version of the SDK
1. Add a dependency exclude on `com.okta.spring:okta-spring-sdk` (and then configure the v2 SDK directly)

**Comment by arvindkrishnakumar-okta** [comment]
@garcger-blk did that help for now (until we upgrade `okta-spring-boot`)?

**Comment by garcger-blk** [comment]
@arvindkrishnakumar-okta yes, @bdemers 2nd suggestion worked out for us (belated thanks, btw)
```xml
<dependency>
	<groupId>com.okta.spring</groupId>
	<artifactId>okta-spring-boot-starter</artifactId>
	<exclusions>
		<exclusion>
			<groupId>com.okta.spring</groupId>
			<artifactId>okta-spring-sdk</artifactId>
		</exclusion>
	</exclusions> 
</dependency>
```
```java
@Configuration
public class ApiConfig {

	@Value("${okta.client.connectionTimeout:30}")
	private String connectionTimeout;

	@Value("${okta.client.orgUrl:reasonable-default}")
	private String orgUrl;

	@Value("${okta.client.proxy.port:8080}")
	private String proxyPort;

	@Value("${okta.client.proxy.host:reasonable-default}")
	private String proxyHost;

	@Value("${okta.client.token:}")
	private String token;

	@Value("${okta.client.requestTimeout:0}")
	private String requestTimeout;

	@Value("${okta.client.rateLimit.maxRetries:4}")
	private String maxRetries;

	@Bean
	public Client client() {
		return Clients.builder()
			.setClientCredentials(new TokenClientCredentials(token))
			.setConnectionTimeout(Integer.parseInt(connectionTimeout))
			.setOrgUrl(orgUrl)
			.setProxy(new Proxy(proxyHost, Integer.parseInt(proxyPort)))
			.setRetryMaxElapsed(Integer.parseInt(requestTimeout))
			.setRetryMaxAttempts(Integer.parseInt(maxRetries))
			.build();
	}
}

```
