### ISSUE TITLE
Unable to login to Org - 404 error

### ISSUE THREAD

**Issue by jamietanna** [okta/okta-sdk-java#509]
I've unexpectedly started receiving this exception today, when it was working fine a couple of days ago:

```
Jan 03 23:21:28 indieauth java[26195]: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
Jan 03 23:21:28 indieauth java[26195]:  at [Source: (ByteArrayInputStream); line: 1, column: 2]
Jan 03 23:21:28 indieauth java[26195]:         at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851) ~[jackson-core-2.11.0.jar!/:2.11.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707) ~[jackson-core-2.11.0.jar!/:2.11.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:632) ~[jackson-core-2.11.0.jar!/:2.11.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2683) ~[jackson-core-2.11.0.jar!/:2.11.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:865) ~[jackson-core-2.11.0.jar!/:2.11.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:757) ~[jackson-core-2.11.0.jar!/:2.11.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4620) ~[jackson-databind-2.11.0.jar!/:2.11.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4469) ~[jackson-databind-2.11.0.jar!/:2.11.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3471) ~[jackson-databind-2.11.0.jar!/:2.11.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.JacksonMapMarshaller.unmarshal(JacksonMapMarshaller.java:86) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.DefaultDataStore.getBody(DefaultDataStore.java:474) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:451) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.DefaultDataStore.lambda$getResourceData$1(DefaultDataStore.java:196) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:208) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:177) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at com.okta.sdk.impl.client.DefaultClient.getUser(DefaultClient.java:2362) ~[okta-sdk-impl-2.0.0.jar!/:2.0.0]
Jan 03 23:21:28 indieauth java[26195]:         at me.jvt.www.indieauth.authenticators.oktaverify.OktaFacade.triggerVerify(OktaFacade.java:31) ~[classes!/:na]
```

[Code for reference](https://gitlab.com/jamietanna/www-api/-/blob/feature/okta-verify-auth/www-api-web/indieauth/src/main/java/me/jvt/www/indieauth/authenticators/oktaverify/OktaFacade.java#L29)

**Comment by arvindkrishnakumar-okta** [comment]
@jamietanna Which version of the SDK are you using? Also, from the stack trace and code that you referenced above, it looks like the error is originating from `client.getUser(userId)` API (not verify API). Ref: https://gitlab.com/jamietanna/www-api/-/blob/feature/okta-verify-auth/www-api-web/indieauth/src/main/java/me/jvt/www/indieauth/authenticators/oktaverify/OktaFacade.java#L31.

**Comment by jamietanna** [comment]
Thanks for the spot! It is indeed the `getUser` failing, and it appears that my Okta tenant domain is no longer present? When trying to connect to the top-level domain for the tenant, I receive a 404 with an HTML login page.

**Comment by arvindkrishnakumar-okta** [comment]
What is the tenant URL you're using?

**Comment by jamietanna** [comment]
https://jamietanna-co.okta.com/

**Comment by arvindkrishnakumar-okta** [comment]
The above domain seems to be valid and present. Which URL are you getting a `404` HTTP error for?

**Comment by jamietanna** [comment]
Although the page looks valid, it's returning a 404:

```
curl -i https://jamietanna-co.okta.com/
HTTP/2 404 
date: Mon, 04 Jan 2021 17:13:37 GMT
content-type: text/html; charset=UTF-8
content-length: 173025
server: Apache
public-key-pins-report-only: pin-sha256="r5EfzZxQVvQpKo3AgYRaT7X2bDO/kj3ACwmxfdT2zt8="; pin-sha256="MaqlcUgk2mvY/RFSGeSwBRkI+rZ6/dxe/DuQfBT/vnQ="; pin-sha256="72G5IEvDEWn+EThf3qjR7/bQSWaS2ZSLqolhnO6iyJI="; pin-sha256="rrV6CLCCvqnk89gWibYT0JO6fNQ8cCit7GGoiVTjCOg="; max-age=60; report-uri="https://okta.report-uri.com/r/default/hpkp/reportOnly"
last-modified: Wed, 24 Jun 2020 22:29:21 GMT
etag: "2a3e1-5a8dc01dbb240"
accept-ranges: bytes
```

And I don't seem to be able to log in via https://login.okta.com/ either

**Comment by arvindkrishnakumar-okta** [comment]
Are you able to login to `https://jamietanna-co.okta.com/` through the browser on supplying the credentials?

**Comment by jamietanna** [comment]
No, nor does the "Need help signing in?" button work

**Comment by arvindkrishnakumar-okta** [comment]
Can you present the 'Network` trace from browser debugging tools when you attempt to login with credentials?

**Comment by jamietanna** [comment]
![2021-01-04-173016_543x397_scrot](https://user-images.githubusercontent.com/3315059/103562168-87894e80-4eb2-11eb-9b32-4aa2dcfe0716.png)
![2021-01-04-172941_1200x346_scrot](https://user-images.githubusercontent.com/3315059/103562170-8821e500-4eb2-11eb-9373-0a9fc9900480.png)

**Comment by arvindkrishnakumar-okta** [comment]
@jamietanna Thanks! Are you using reverse proxy?

**Comment by jamietanna** [comment]
No I'm not ---- On Mon, 04 Jan 2021 17:36:01 +0000  notifications@github.com  wrote ----
@jamietanna Thanks! Are you using reverse proxy?

**Comment by arvindkrishnakumar-okta** [comment]
Are you aware of any recent configuration setting changes to your Okta domain in the recent times?

**Comment by jamietanna** [comment]
No I'm not. It last worked late last week (can't remember exactly when) and I've not had any emails about the account

**Comment by arvindkrishnakumar-okta** [comment]
Recommend you to post this on the Okta Developer Forum (https://devforum.okta.com) instead. For urgent issues contact support@okta.com. Issues in this repository are reserved for bug reports and feature requests.

**Comment by jamietanna** [comment]
Np, thanks for helping
