### ISSUE TITLE
No enum constant com.okta.sdk.resource.application.ApplicationSignOnMode.RADIUS_FOR_GENERIC_APP

### ISSUE THREAD

**Issue by phi1ipp** [okta/okta-sdk-java#539]
I'm trying to filter apps by their type with the snippet below and ran into the runtime exception (library version 3.0.2)
```
    client.listApplications()
        .filter { app -> app.signOnMode == ApplicationSignOnMode.SAML_2_0 }
        .forEach { app ->
        println(app)
    }
```

> Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.okta.sdk.resource.application.ApplicationSignOnMode.RADIUS_FOR_GENERIC_APP
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.okta.sdk.impl.resource.EnumConverter.fromValue(EnumConverter.java:56)
	at com.okta.sdk.impl.resource.AbstractPropertyRetriever.getEnumProperty(AbstractPropertyRetriever.java:282)
	at com.okta.sdk.impl.resource.AbstractPropertyRetriever.getEnumProperty(AbstractPropertyRetriever.java:272)
	at com.okta.sdk.impl.resource.application.DefaultApplication.getSignOnMode(DefaultApplication.java:205)
	at MainKt.main(main.kt:25)
	at MainKt.main(main.kt)

**Comment by arvindkrishnakumar-okta** [comment]
@phi1ipp Thanks for posting!

Presently, below is the exhaustive list of `ApplicationSignOnMode` values that the SDK understands:

https://github.com/okta/okta-management-openapi-spec/blob/master/resources/spec.yaml#L7288-L7298

I'll check to see if the spec is missing an update to include `RADIUS_FOR_GENERIC_APP` in `ApplicationSignOnMode` enum.

**Comment by phi1ipp** [comment]
@arvindkrishnakumar-okta , thank you for a prompt response. I think it's missing in the enum as per my observation

**Comment by arvindkrishnakumar-okta** [comment]
Internal Ref: OKTA-370307
