### ISSUE TITLE
listGroups with filter not working

### ISSUE THREAD

**Issue by slunker** [okta/okta-sdk-java#593]
### I'm submitting a
  - [X ] bug report

### Background info
Hello Okta Team, a call to ```Client.listGroups(null, "profile.name eq \"foo\"", null);``` fails with
```
{
    "errorCode": "E0000031",
    "errorSummary": "Invalid search criteria.",
    "errorLink": "E0000031",
    "errorId": "oaeNkIcHWlCQGqYukyKZVBaMw",
    "errorCauses": []
}
```
It looks like there's a bug in ```com.okta.sdk.impl.client.DefaultClient``` class in method ```listGroups(String q, String filter, String expand)``` on line 593: ```if (filter != null) queryArgs.put("filter", filter);```

The correct name of query parameter used in the ```/api/v1/groups``` endpoint is ```search``` and not ```filter```

### Expected behavior

A list of groups matching the search criteria is returned.

### What went wrong?
This is the exception stack trace:
```
com.okta.sdk.resource.ResourceException: HTTP 400, Okta E0000031 (Invalid search criteria.), ErrorId oae9WvkqQyqT8qK0G0CnxdZEw
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:475) ~[okta-sdk-impl-4.0.0.jar:4.0.0]
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$getResourceData$2(DefaultDataStore.java:210) ~[okta-sdk-impl-4.0.0.jar:4.0.0]
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47) ~[okta-sdk-impl-4.0.0.jar:4.0.0]
	at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34) ~[okta-sdk-impl-4.0.0.jar:4.0.0]
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[okta-sdk-impl-4.0.0.jar:4.0.0]
	at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42) ~[okta-sdk-impl-4.0.0.jar:4.0.0]
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[okta-sdk-impl-4.0.0.jar:4.0.0]
	at com.okta.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:222) ~[okta-sdk-impl-4.0.0.jar:4.0.0]
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:178) ~[okta-sdk-impl-4.0.0.jar:4.0.0]
	at com.okta.sdk.impl.client.DefaultClient.listGroups(DefaultClient.java:598) ~[okta-sdk-impl-4.0.0.jar:4.0.0]
```

### SDK Version
4.0.0

**Comment by VitaliiTytarenko-okta** [comment]
@slunker 
Thank you for reporting!
We will fix it soon and let you know.

**Comment by slunker** [comment]
thanks @VitaliiTytarenko-okta

**Comment by VitaliiTytarenko-okta** [comment]
Internal ref: `OKTA-406629`
