### ISSUE TITLE
User.listFactors can fail for some user statuses

### ISSUE THREAD

**Issue by dspasojevic** [okta/okta-sdk-java#646]
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

When listing factors on a user retrieved via `getUser` or `listUsers`, a ResourceException is thrown if the user have been `DEPROVISIONED`.

### Expected behavior

A list of empty factors is returned.

### What went wrong?

`listFactors` throws a ResourceException:

```
com.okta.sdk.resource.ResourceException: HTTP 404, Okta E0000007 (Not found: Resource not found: <id of the user> (User)), ErrorId oaeZK6Mki40TTK_dHD1W7Xkzg
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:477)
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$getResourceData$2(DefaultDataStore.java:212)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
	at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:224)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:180)
	at com.okta.sdk.impl.resource.user.DefaultUser.listFactors(DefaultUser.java:449)
```

### Steps to reproduce

This behaviour can be reproduced by fetching a deactivated user then attempting to list the factors:
```
        val deactivatedUserId = "<snip>"
        val user = client.getUser(deactivatedUserId)
        val factors = user.listFactors() // Will throw an exception
```
### SDK Version

5.0.0

**Comment by sergiishamrai-okta** [comment]
Hi @dspasojevic,
Thanks for your question.

I've checked Factors API behavior, and I can say that the user should be active to perform the List enrolled Factors operation.
It's not a bug of the SDK.
You can play with this method via Postman. Factor API docs is [here](https://developer.okta.com/docs/reference/api/factors/)

**Comment by dspasojevic** [comment]
Thanks @sergiishamrai-okta.

Is it definitely only active users that can have factors listed? E.g. it should not be called with suspended, etc. If so, that makes things easy for us, we can work around it.

I had checked the doco that you linked, but it doesn't seem to mention that the user must be active when [listing factors](https://developer.okta.com/docs/reference/api/factors/#list-enrolled-factors). That *might* make things more clear for future users 🤷.

Thanks again. Since this is working as designed, I'll close.
