### ISSUE TITLE
Invalid cookie header

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [okta/okta-sdk-java#687]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

```
WARNING: Invalid cookie header: "set-cookie: Okta_Verify_Autopush_-3808598=false;Version=1;Path=/;Max-Age=31536000;Secure;Expires=Fri, 30 Dec 2022 03:37:45 GMT;HttpOnly". Invalid 'expires' attribute: Fri, 30 Dec 2022 03:37:45 GMT
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:751)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:749)
	at com.okta.tools.helpers.RoleHelper.chooseAwsRoleToAssume(RoleHelper.java:103)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:133)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:102)
	at com.okta.tools.WithOkta.main(WithOkta.java:28)
```

### Expected behavior

It should have authenticated

### What went wrong?

See above

### Steps to reproduce

```
 java -jar /usr/local/share/java/okta-aws-cli-3.0.0.jar test sts get-caller-identity
```

This looks like a bug in the httpclient library. It may be a simple matter of upgrading.

### SDK Version

3.0.0

**Comment by krestivo-kdinfotech** [comment]
https://stackoverflow.com/questions/36473478/fixing-httpclient-warning-invalid-expires-attribute-using-fluent-api related maybe

**Comment by krestivo-kdinfotech** [comment]
And it looks like 5ba91fc737243a308c48e252531e046753af4b79 should have fixed this

**Comment by sergiishamrai-okta** [comment]
Hi @krestivo-kdinfotech,
Thank you for your question, I'll try to reproduce this and get back to you soon.

**Comment by sergiishamrai-okta** [comment]
Internal ref: [OKTA-456883](https://oktainc.atlassian.net/browse/OKTA-456883)

**Comment by krestivo-kdinfotech** [comment]
This may be my error with jar vs class path. I will check again

**Comment by krestivo-kdinfotech** [comment]
It was my error; closing.  When running awscli or okta-listroles, no problem, since it uses the httpclient from the uberjar release.

However, I am still seeing this:

```
 awscli sts get-caller-identity
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:751)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:749)
	at com.okta.tools.helpers.RoleHelper.chooseAwsRoleToAssume(RoleHelper.java:103)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:133)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:102)
	at com.okta.tools.WithOkta.main(WithOkta.java:28)
$ okta-listroles
[]
```

But I suspect this is unrelated

**Comment by bdemers** [comment]
@krestivo-kdinfotech It looks like you have the wrong repo, if you are still running into this issue, please open an issue in: https://github.com/oktadev/okta-aws-cli-assume-role/

Thanks!
