### ISSUE TITLE
Retry operation if response is invalid.

### ISSUE THREAD

**Issue by gantzm** [okta/okta-sdk-java#82]
We often times see stuff like the snippet below in our logs.  Would it be possible if the Okta servers don't respond with JSON that the operation be retried?  I believe this is occurring when something really bad happens on the server side and it returns an html error message.

``
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.http.conn.EofSensorInputStream@22504d29; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2689)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3756)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2123)
        at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1650)
        at com.okta.sdk.framework.JsonApiClient.unmarshall(JsonApiClient.java:69)
        at com.okta.sdk.framework.ApiClient.extractError(ApiClient.java:322)
        at com.okta.sdk.framework.ApiClient.checkResponse(ApiClient.java:313)
        at com.okta.sdk.framework.ApiClient.unmarshallResponse(ApiClient.java:286)
        at com.okta.sdk.framework.ApiClient.get(ApiClient.java:156)
        at com.okta.sdk.clients.UserApiClient.getUser(UserApiClient.java:146)

**Comment by bdemers** [comment]
@gantzm defiantly an error. You are probably right, I'm guessing the payload was an HTTP error page.

Any idea on what the response code was?

**Comment by gantzm** [comment]
@bdemers Unfortunately the response code isn't logged.  I have another app that doesn't use the SDK that runs into the same problem though.  I'll try and comb through those logs and see if I can find a response code.  Worst case maybe I can submit a pull request that would capture the JSON parse error and log the response code and content.

**Comment by bdemers** [comment]
Closing, please re-open if you can reproduce
